# -*- coding: utf-8 -*-
"""Aula data science

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/Amad3eu/98093d6b891aa272935fa92c4eebff8b/aula-data-science.ipynb
"""

import pandas as pd 
uri = "https://raw.githubusercontent.com/alura-cursos/introducao-a-data-science/master/aula4.1/movies.csv"
filmes = pd.read_csv(uri)
filmes.head()

import pandas as pd 
uri = "https://raw.githubusercontent.com/alura-cursos/introducao-a-data-science/master/aula4.1/movies.csv"
filmes = pd.read_csv(uri)
filmes.head()

filmes.columns
filmes.head()

uri = "https://raw.githubusercontent.com/alura-cursos/introducao-a-data-science/master/aula1.2/ratings.csv"
notas = pd.read_csv(uri)
notas.head()

notas.columns =["usuarioId", "filmeId", "nota", "momento"]
notas.head()

notas["nota"].head() #series

notas ["nota"].unique()

notas["nota"].mean()

notas["nota"].min()

notas .describe()

# 1, 3, 5 ==> media = 3
 #1, 3, 3, 7
 media = (1+3+3+7) / 4
 media

"""#mediana median 580 580"""

import seaborn as sns
print(sns.__version__)

import pandas as pd

notas['nota'].unique()

print("Media",notas['nota'].mean())
print("Mediana",notas['nota'].median())

notas.nota.head()

notas['nota'].value_counts()

notas.nota.plot(kind='hist')

notas.nota.describe()

import seaborn as sns

sns.boxplot(notas.nota)

notas.head()

notas.query("filmeId==1").nota.mean()

notas.query("filmeId==2").nota.mean()

medias_por_filme = notas.groupby("filmeId").mean().nota
medias_por_filme.head()

medias_por_filme.plot(kind='hist')

import matplotlib.pyplot as plt

plt.figure(figsize=(5,8))
sns.boxplot(y=medias_por_filme)

medias_por_filme.describe()

sns.distplot(medias_por_filme)

plt.hist(medias_por_filme)
plt.title("Histograma das médias dos filmes")